from enum import Enum


class Categoria(Enum):
    NO_RECONOCIDO = 1
    ENTERO = 2
    DECIMAL = 3
    IDENTIFICADOR = 4
    PALABRA_RESERVADA = 5
    OPERADOR_ARITMETICO = 6
    OPERADOR_COMPARACION = 7
    OPERADOR_LOGICO = 8
    OPERADOR_ASIGNACION = 9
    OPERADOR_INCREMENTO = 10
    OPERADOR_DECREMENTO = 11
    PARENTESIS = 12
    LLAVES = 13
    TERMINAL = 14
    SEPARADOR = 15
    HEXADECIMAL = 16
    CADENA_CARACTERES = 17
    COMENTARIO_LINEA = 18
    COMENTARIO_BLOQUE = 19


state = Categoria.ENTERO
print(state)
